name: flutter_frontend
description: "This is an app that will be used by students to book residential houses remotely and by landlords to advertise their vacant houses. The school admin will also be using the app to track where university students resides"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.8.0
  flutter_riverpod: ^2.6.1
  hooks_riverpod: ^2.6.1
  url_strategy: ^0.3.0

  dotenv: ^4.2.0
  google_fonts: ^6.2.1
  flutter_dotenv: ^5.2.1
  dio: ^5.8.0+1
  logger: ^2.5.0

  flutter_hooks: ^0.20.5
  image_picker: ^1.1.2
  email_validator: ^3.0.0
  google_sign_in: ^6.2.2
  flutter_signin_button: ^2.0.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0

  #firebase
  firebase_auth: ^5.4.1
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1

  google_maps_flutter: ^2.11.0
  google_maps_flutter_web: ^0.5.12

  shared_preferences: ^2.5.2
  file_picker: ^9.2.3

  google_generative_ai: ^0.4.6
  http: ^1.3.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


