// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:url_strategy/url_strategy.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      setPathUrlStrategy();
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAMTvrqnox4W0Fg0u-Eb69O45LIiN7NdY',
    appId: '1:820226507396:web:d42d38333f42a651d378d1',
    messagingSenderId: '820226507396',
    projectId: 'residential-tracker-aad98',
    authDomain: 'residential-tracker-aad98.firebaseapp.com',
    storageBucket: 'residential-tracker-aad98.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCYIgrhD0NinGuXUkowBVazuJH4fvMGhs',
    appId: '1:820226507396:android:1859da5db02f372ed378d1',
    messagingSenderId: '820226507396',
    projectId: 'residential-tracker-aad98',
    storageBucket: 'residential-tracker-aad98.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAMTvrqnox4W0Fg0u-Eb69O45LIiN7NdY',
    appId: '1:820226507396:web:db2edec0b27e0055d378d1',
    messagingSenderId: '820226507396',
    projectId: 'residential-tracker-aad98',
    authDomain: 'residential-tracker-aad98.firebaseapp.com',
    storageBucket: 'residential-tracker-aad98.firebasestorage.app',
  );
}
